- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull calculator image
      docker_image:
        name: meetmandhane/calculator
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator meetmandhane/calculator


